In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP preprocessing
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Machine learning
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df = pd.read_csv("zelda.csv")

df.head()

               Time    0  0.0625  0.125  ...  23.4375  23.5  23.5625 23.625
0               NaN  NaN     NaN    NaN  ...      NaN   NaN      NaN    NaN
1          Square 1  NaN     NaN    NaN  ...      NaN   NaN      NaN    NaN
2  SQ1 Sweep Period    0     NaN    NaN  ...      NaN   NaN      NaN    NaN
3        SQ1 Negate    0     NaN    NaN  ...      NaN   NaN      NaN    NaN
4         SQ1 Shift    0     NaN    NaN  ...      NaN   NaN      NaN    NaN

[5 rows x 380 columns]

In [3]:
df.info()
df.describe()

# Check missing values
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Columns: 380 entries, Time to 23.625
dtypes: float64(271), str(109)
memory usage: 2.9 MB

Time        963
0           968
0.0625     1001
0.125      1001
0.1875     1001
           ...
23.375     1001
23.4375    1001
23.5       1001
23.5625    1001
23.625     1001
Length: 380, dtype: int64

In [4]:
import re

stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def clean_text(text):
    
    text = str(text).lower()
    
    # Remove punctuation
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    
    words = text.split()
    
    # Remove stopwords + stemming
    words = [stemmer.stem(word) for word in words if word not in stop_words]
    
    return " ".join(words)

In [7]:
print(df.columns)

Index(['Time', '0', '0.0625', '0.125', '0.1875', '0.25', '0.3125', '0.375',
       '0.4375', '0.5',
       ...
       '23.0625', '23.125', '23.1875', '23.25', '23.3125', '23.375', '23.4375',
       '23.5', '23.5625', '23.625'],
      dtype='str', length=380)

In [9]:
df.head()

               Time    0  0.0625  0.125  ...  23.4375  23.5  23.5625 23.625
0               NaN  NaN     NaN    NaN  ...      NaN   NaN      NaN    NaN
1          Square 1  NaN     NaN    NaN  ...      NaN   NaN      NaN    NaN
2  SQ1 Sweep Period    0     NaN    NaN  ...      NaN   NaN      NaN    NaN
3        SQ1 Negate    0     NaN    NaN  ...      NaN   NaN      NaN    NaN
4         SQ1 Shift    0     NaN    NaN  ...      NaN   NaN      NaN    NaN

[5 rows x 380 columns]

In [11]:
print("Columns:", df.columns)
print(df.head())

Columns: Index(['Time', '0', '0.0625', '0.125', '0.1875', '0.25', '0.3125', '0.375',
       '0.4375', '0.5',
       ...
       '23.0625', '23.125', '23.1875', '23.25', '23.3125', '23.375', '23.4375',
       '23.5', '23.5625', '23.625'],
      dtype='str', length=380)
               Time    0  0.0625  0.125  ...  23.4375  23.5  23.5625 23.625
0               NaN  NaN     NaN    NaN  ...      NaN   NaN      NaN    NaN
1          Square 1  NaN     NaN    NaN  ...      NaN   NaN      NaN    NaN
2  SQ1 Sweep Period    0     NaN    NaN  ...      NaN   NaN      NaN    NaN
3        SQ1 Negate    0     NaN    NaN  ...      NaN   NaN      NaN    NaN
4         SQ1 Shift    0     NaN    NaN  ...      NaN   NaN      NaN    NaN

[5 rows x 380 columns]

In [14]:
print(df.columns)

Index(['Time', '0', '0.0625', '0.125', '0.1875', '0.25', '0.3125', '0.375',
       '0.4375', '0.5',
       ...
       '23.0625', '23.125', '23.1875', '23.25', '23.3125', '23.375', '23.4375',
       '23.5', '23.5625', '23.625'],
      dtype='str', length=380)

In [17]:
# Import libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Example dataset (replace with your own dataset)
from sklearn.datasets import load_iris
data = load_iris()

X = data.data      # features
y = data.target    # labels

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create the model
model = LogisticRegression(max_iter=200)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [18]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 1.0

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30